# Generated by Django 5.1.1 on 2024-09-05 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_title', models.CharField(default='No Subject', max_length=100)),
                ('sender', models.EmailField(default='no-reply@example.com', max_length=254)),
                ('content', models.TextField(default='No content provided')),
                ('received_date', models.DateTimeField(default=datetime.datetime(2024, 1, 1, 12, 0))),
            ],
        ),
    ]
