# Generated by Django 5.0.7 on 2024-08-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
